/**
 * @brief [filter was designed for a Fs of 48K, Fpass of 10K, Fstop of 12K to filter the guitar signal as input to the effects]
 */

/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 23-Oct-2015 21:55:56
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 48
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

#ifndef FIR_LOWPASS_H
#define FIR_LOWPASS_H


extern const int BL = 48;
extern const float B[48] = {
  -0.004430111032, -0.01099904813, -0.01126175001,0.0002033681376,  0.01301323157,
    0.01085966919,-0.003508112626,-0.007573440205, 0.007321337238,  0.01779179275,
    0.00299743237, -0.01648918167,-0.005753920414,    0.023352677,  0.02093379572,
   -0.01855988614, -0.03185524419,  0.01633086242,  0.05587054044, 0.002798119327,
   -0.08579733968, -0.04264193028,   0.1839655936,   0.4115542471,   0.4115542471,
     0.1839655936, -0.04264193028, -0.08579733968, 0.002798119327,  0.05587054044,
    0.01633086242, -0.03185524419, -0.01855988614,  0.02093379572,    0.023352677,
  -0.005753920414, -0.01648918167,  0.00299743237,  0.01779179275, 0.007321337238,
  -0.007573440205,-0.003508112626,  0.01085966919,  0.01301323157,0.0002033681376,
   -0.01126175001, -0.01099904813,-0.004430111032
};


#endif