/**
 * @brief [Filter was designed for a stop of 20, pass 80 to 300 and stop by 400]
 */

/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 27-Oct-2015 23:41:08
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */



#ifndef IIR_LOW
#define IIR_LOW

#define MWSPT_NSEC 15





extern int NL_lowpass[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
extern float NUM_lowpass[MWSPT_NSEC][3] = {
  {
     0.3307475774541,                 0,                 0 
  },
  {
                   1,   -1.995765299257,                 1 
  },
  {
     0.3307475774541,                 0,                 0 
  },
  {
                   1,   -1.999937642329,                 1 
  },
  {
     0.4850701119944,                 0,                 0 
  },
  {
                   1,   -1.994418717076,                 1 
  },
  {
     0.4850701119944,                 0,                 0 
  },
  {
                   1,   -1.999952702975,                 1 
  },
  {
     0.1833767197203,                 0,                 0 
  },
  {
                   1,   -1.985927486711,                 1 
  },
  {
     0.1833767197203,                 0,                 0 
  },
  {
                   1,   -1.999981281325,                 1 
  },
  {
     0.0192205692055,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
                   1,                 0,                 0 
  }
};

extern int DL_lowpass[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
extern float DEN_lowpass[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.995510074032,   0.9979090166984 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.999441980373,   0.9995519658117 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.991365039596,   0.9933277937981 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.998119732344,   0.9982537785213 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.988223124768,   0.9894194726238 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.995244192027,    0.995463410735 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.990214893189,   0.9907265932943 
  },
  {
                   1,                 0,                 0 
  }
};

#endif